Bugfix/18529 switch vip when sync interface down
redBorder/redborder-manager pull request #193
Opened 2024-11-13 09:10 UTC by nilsver

2024-11-18 15:40 UTC, ljblancoredborder requested changes
(local) manager is defined as local variable, while not being used in the function. Remove it if not used
knowing how input_json is, it will be fine to comment the structure: I suppose is {node1:{a:b,c:d},node2:{a:b,c:d}}

2024-11-18 17:22 UTC, ljblancoredborder requested changes
remove local variable manager, since is not being used

2024-11-21 15:52 UTC, rgomezborder commented on resources/bin/rb_check_interface.sh
```sh
#!/bin/bash

check_sync_interface_status() {
    local manager=$1
    local sync_ip=$2

    if ! ping -c 1 "$sync_ip" &> /dev/null; then
        echo "Sync interface down for $manager, restarting keepalived..."
        systemctl restart keepalived
    fi
}

# Ensure the input is passed as an argument
if [[ -z "$1" ]]; then
    echo "Error: JSON input is required."
    exit 1
fi

input_json="$1"

# Iterate through the managers in the JSON
for manager in $(echo "$input_json" | jq -r 'keys[]'); do
    sync_ip=$(echo "$input_json" | jq -r ".\"$manager\".ipaddress_sync")
    check_sync_interface_status "$manager" "$sync_ip"
done
```

2024-11-22 13:48 UTC, ljblancoredborder approved these changes

2024-11-28 09:42 UTC, closed without merging